<header class="row">
    <h1 class="col-md-9">Coins</h1>
    <div class="col-md-3">
        <a class="pull-right btn btn-sm btn-success" href="<?php echo $this->url('application/default', array(
            'controller' => 'coin',
            'action' => 'add'
        ));?>">Add Coin</a>
    </div>
</header>
    
<table class="table">
    <thead>
        <tr>
            <th>Year</th>
            <th>Mintage</th>
            <th>Obverse Design</th>
            <th>Reverse Design</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($this->coins as $coin):?>
        <tr>
            <td><?php echo $coin->getYear(); ?></td>
            <td><?php echo $coin->getMintage(); ?></td>
            <td><?php echo $coin->getObverseDesign(); ?></td>
            <td><?php echo $coin->getReverseDesign(); ?></td>
            <td style="width: 1%;" nowrap>
                <a class="btn btn-sm btn-warning" href="<?php echo $this->url('application/default', array(
                    'controller' => 'coin',
                    'action' => 'edit',
                    'id' => $coin->getId()
                )); ?>">Edit</a>
                <a class="btn btn-sm btn-danger" href="<?php echo $this->url('application/default', array(
                    'controller' => 'coin',
                    'action' => 'delete',
                    'id' => $coin->getId()
                )); ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
