<h1>Monarchs</h1>
<table class="table">
    <thead>
        <tr>
            <th>Monarch</th>
            <th>House</th>
            <th>Reign Start</th>
            <th>Reign End</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($this->monarchs as $monarch):?>
        <tr>
            <td><?php echo $monarch->getName(); ?></td>
            <td><?php echo $monarch->getHouse(); ?></td>
            <td><?php echo date_format($monarch->getReignStart(), 'd/m/Y'); ?></td>
            <td><?php echo $monarch->getReignEnd(); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
