<h1>Monarchs</h1>
<table class="table">
    <thead>
        <tr>
            <th>Monarch</th>
            <th>House</th>
            <th>Reign Start</th>
            <th>Reign End</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($this->monarchs as $monarch):?>
        <tr>
            <td><?php echo $monarch; ?></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
