
<h1><?php echo $this->denomination; ?></h1>
<?php foreach ($this->types as $type): ?>

    <h2><?php echo $type->getMonarch()->getName(); ?></h2>
    Diameter: <?php echo $type->getDiameter(); ?><br>
    Weight: <?php echo $type->getWeight(); ?><br>
    Metal: <?php echo $type->getMetal(); ?><br>
    
    <table class="table">
    <?php foreach($type->getCoins() as $coin): ?>
        <tr>
            <?php $img = $coin->getReverseImage() ?: $coin->getObverseImage();?>
            <td><img height="96" src="/images/<?php echo $img; ?>"</td>
            <td><?php echo $coin->getYear(); ?></td>
            <td><?php echo $coin->getMintage(); ?></td>
            <td><?php echo $coin->getObverseDesign(); ?></td>
            <td><?php echo $coin->getReverseDesign(); ?></td>
        </tr>
    <?php endforeach; ?>
    </table>

<?php endforeach; ?>


