
<h1><?php echo $this->denomination; ?></h1>
<?php foreach ($this->types as $type): ?>

    <h2><?php echo $type->getMonarch()->getName(); ?></h2>
    <p>Diameter: <?php echo $type->getDiameter(); ?></p>
    <p>Metal: <?php echo $type->getMetal(); ?></p>
    
    <table class="table">
    <?php foreach($type->getCoins() as $coin): ?>
        <tr>
            <td><?php echo $coin->getYear(); ?></td>
            <td><?php echo $coin->getMintage(); ?></td>
            <td><?php echo $coin->getObverseDesign(); ?></td>
            <td><?php echo $coin->getReverseDesign(); ?></td>
        </tr>
    <?php endforeach; ?>
    </table>

<?php endforeach; ?>


