<div class="jumbotron">
    <h1>UK Coin Collection</h1>
    <p>Coins of the United Kingdom. Use the links below to view the different coins types.</p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Pre-Decimal</h3>
            </div>
            <div class="panel-body">
                <ul>
                    <li><a href="#">Half Farthing</a></li>
                    <li><a href="#">Farthing</a></li>
                    <li><a href="#">Half Penny</a></li>
                    <li><a href="#">Penny</a></li>
                    <li><a href="#">Threepence</a></li>
                    <li><a href="#">Groat</a></li>
                    <li><a href="#">Sixpence</a></li>
                    <li><a href="#">Shilling</a></li>
                    <li><a href="#">Florin</a></li>
                    <li><a href="#">Half Crown<a></li>
                    <li><a href="#">Crown</a></li>
                </ul>            
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Decimal</h3>
            </div>
            <div class="panel-body">
                <ul>
                    <li><a href="#">Half pence</a></li>
                    <li><a href="#">One Pence</a></li>
                    <li><a href="#">Two Pence</a></li>
                    <li><a href="#">Five Pence</a></li>
                    <li><a href="#">Ten Pence</a></li>
                    <li><a href="#">Twenty Pence</a></li>
                    <li><a href="#">Twenty Five Pence</a></li>
                    <li><a href="#">Fifty Pence</a></li>
                    <li><a href="#">One Pound<a></li>
                    <li><a href="#">Two Pounds</a></li>
                    <li><a href="#">Five Pounds</a></li>
                </ul>            
            </div>
        </div>
    </div>

    
</div>
