<div class="jumbotron">
    <h1>UK Coin Collection</h1>
    <p>Coins of the United Kingdom. Use the links below to view the different coins types.</p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Pre-Decimal</h3>
            </div>
            <div class="panel-body">
                <ul>
                <?php $denominations = array('Half Farthing', 'Farthing', 'Half Penny', 'Penny',
                    'Threepence', 'Groat', 'Sixpence', 'Shilling', 'Florin', 'Half Crown', 'Crown'); ?>
                <?php foreach ($denominations as $denomination): ?>
                    <li><a href="<?php echo $this->url('application/default', array(
                            'controller' => 'type',
                            'action'     => 'denomination',
                            'id' => urlEncode($denomination)
                    ));?>"><?php echo $denomination; ?></a></li>
                <?php endforeach; ?>
                </ul>            
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Decimal</h3>
            </div>
            <div class="panel-body">
                <ul>
                <?php $denominations = array('Half pence', 'One pence', 'Two pence', 'Five pence',
                    'Ten pence', 'Twenty pence', 'Fifty pence', 'One pound', 'Two pounds', 'Five pounds'); ?>
                <?php foreach ($denominations as $denomination): ?>
                   
                    <li><a href="<?php echo $this->url('application/default', array(
                            'controller' => 'type',
                            'action'     => 'denomination',
                            'id' => urlEncode($denomination)
                    ));?>"><?php echo $denomination; ?></a></li>
                <?php endforeach; ?>
                </ul>            
            </div>
        </div>
    </div>

    
</div>
