<div id="home" class="row" style="background-color: #242424; color: #ddd">
    
    <div class="col-md-3">
        <img src="/img/coins.jpg">
    </div>
    
    <div class="col-md-9">
            <h1>United Kingdom Coin Collection</h1>
            <p>Coins of the United Kingdom. Use the links below to view the different coins types.</p>
    </div>
    
    <div class="col-md-3">
        <div class="list">
            <div class="list-header">
                <h2>Pre-Decimal</h2>
            </div>
            <div>
                <ul>
                <?php $denominations = array('Half Farthing', 'Farthing', 'Half Penny', 'Penny',
                    'Threepence', 'Groat', 'Sixpence', 'Shilling', 'Florin', 'Half Crown', 'Crown'); ?>
                <?php foreach ($denominations as $denomination): ?>
                    <li><a href="<?php echo $this->url('application/default', array(
                            'controller' => 'type',
                            'action'     => 'denomination',
                            'id' => urlEncode($denomination)
                    ));?>"><?php echo $denomination; ?></a></li>
                <?php endforeach; ?>
                </ul>            
            </div>
        </div>
    </div>
    
    <div class="col-md-3">
        <div class="list">
            <div class="list-header">
                <h2>Decimal</h2>
            </div>
            <div>
                <ul>
                <?php $denominations = array('Half pence', 'One pence', 'Two pence', 'Five pence',
                    'Ten pence', 'Twenty pence', 'Twenty-five pence', 'Fifty pence', 'One pound', 'Two pounds', 'Five pounds'); ?>
                <?php foreach ($denominations as $denomination): ?>
                   
                    <li><a href="<?php echo $this->url('application/default', array(
                            'controller' => 'type',
                            'action'     => 'denomination',
                            'id' => urlEncode($denomination)
                    ));?>"><?php echo $denomination; ?></a></li>
                <?php endforeach; ?>
                </ul>            
            </div>
        </div>
    </div>
    
    <div class="col-md-3">
        <div class="list">
            <div class="list-header">
                <h2>Gold</h2>
            </div>
            <div>
                <ul>
                <?php $denominations = ['Half Sovereign', 'Half guinea', 'Sovereign', 'Guinea']; ?>
                <?php foreach ($denominations as $denomination): ?>
                   
                    <li><a href="<?php echo $this->url('application/default', array(
                            'controller' => 'type',
                            'action'     => 'denomination',
                            'id' => urlEncode($denomination)
                    ));?>"><?php echo $denomination; ?></a></li>
                <?php endforeach; ?>
                </ul>            
            </div>
        </div>
    </div>
    
</div>
