<h1><?php echo $this->type; ?></h1>


<h3>Victoria <small>Godless and Gothic</small></h2>

<h3>Victoria <small>Jubilee Head</small></h2>

<h3>Victoria <small>Old, Veiled or Widow Head</small></h2>
<table class="table table-condensed table-bordered">
    <tbody>
        <tr>
            <th>Year</th>
            <th>Mintage</th>
            <th>Condition</th>
            <th>Est. Value</th>
        </tr>
        <?php foreach ($this->coins as $coin): ?>
        <tr>
            <td>1893</td>
            <td>1,666,103</td>
            <td></td>
            <td></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<br><br></br>
<hr>

<table class="table">
    <tbody>
        <?php foreach ($this->coins as $coin): ?>
        <tr>
            <td><?php echo $coin;?>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
